version: "3"

services:
  db:
    image: postgres
    restart: always
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data/
#    env_file: .env-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    # command: /entrypoint.sh #python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/appboxo
      - /static:/static
    expose:
      - "8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  redis:
    image: redis
    ports:
      - 6379:6379
  nginx:
    build: ./nginx
    ports:
      - 8000:8000
    volumes:
      - /static:/static
    depends_on:
      - web
